const express = require("express")
const router = express.Router()
const {upload} = require("../Middleware/Multer")
const {addproduct,getlatestproducts,getbestsellingproducts,getallwatches,getProductById,updateProductById,deleteProduct,outofstockproductcount} = require("../controller/product")
const {authenticateToken} = require("../Middleware/productMiddleware")
router.post("/addproducts",authenticateToken,upload.single("productPic"),addproduct)
router.get("/getlatestproduct",getlatestproducts)
router.get("/getbestsellingproduct",getbestsellingproducts)
router.get("/getallwatches",getallwatches)
router.get("/getproductbyid/:id",getProductById)
router.post("/updatedProduct/:id",authenticateToken,updateProductById)
router.delete("/deleteproduct/:id",authenticateToken,deleteProduct)
router.get("/getoutstockcount",outofstockproductcount)
module.exports = router