const express = require("express")
const router = express.Router()
const {registerUser,loginuser,getallusers,getexistAdmin,updateadmindetails,updateUserDetails,getuserdetails,NoOfUsers,monthlyNewUsers} = require("../controller/Usercontroller")
const {authenticateToken} = require("../Middleware/Ordermiddleware")
const {authenticateToken1,authenticateToken2} = require("../Middleware/StripeMiddleware")
router.post("/register",registerUser)
router.post("/login",loginuser)
router.get("/getusers",authenticateToken,getallusers)
router.post("/updateAdmin",authenticateToken,updateadmindetails)
router.get("/getAdmin",authenticateToken,getexistAdmin)
router.post("/updateUserDetails",authenticateToken1,updateUserDetails)
router.post("/getuser",authenticateToken2,getuserdetails)
router.get("/noOfusers",NoOfUsers)
router.get("/monthNewUsers",monthlyNewUsers)
module.exports = router